entries:
- member_id: M0
  task_type: sc
  base_seed: 42
  start_index: 0
  count: 600
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:02Z'
  trial_id: trial_3
  fixed_target:
    rail: 1
    port: sc_port_1
- member_id: M1
  task_type: sfp
  base_seed: 42
  start_index: 100000
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:09Z'
  trial_id: trial_1
  fixed_target:
    rail: 0
    port: sfp_port_0
- member_id: M1
  task_type: sfp
  base_seed: 42
  start_index: 100120
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:10Z'
  trial_id: trial_2
  fixed_target:
    rail: 1
    port: sfp_port_0
- member_id: M2
  task_type: sfp
  base_seed: 42
  start_index: 200000
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:11Z'
  trial_id: trial_1
  fixed_target:
    rail: 0
    port: sfp_port_0
- member_id: M2
  task_type: sfp
  base_seed: 42
  start_index: 200120
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:12Z'
  trial_id: trial_2
  fixed_target:
    rail: 1
    port: sfp_port_0
- member_id: M3
  task_type: sfp
  base_seed: 42
  start_index: 300000
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:13Z'
  trial_id: trial_1
  fixed_target:
    rail: 0
    port: sfp_port_0
- member_id: M3
  task_type: sfp
  base_seed: 42
  start_index: 300120
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:14Z'
  trial_id: trial_2
  fixed_target:
    rail: 1
    port: sfp_port_0
- member_id: M4
  task_type: sfp
  base_seed: 42
  start_index: 400000
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:16Z'
  trial_id: trial_1
  fixed_target:
    rail: 0
    port: sfp_port_0
- member_id: M4
  task_type: sfp
  base_seed: 42
  start_index: 400120
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:17Z'
  trial_id: trial_2
  fixed_target:
    rail: 1
    port: sfp_port_0
- member_id: M5
  task_type: sfp
  base_seed: 42
  start_index: 500000
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:18Z'
  trial_id: trial_1
  fixed_target:
    rail: 0
    port: sfp_port_0
- member_id: M5
  task_type: sfp
  base_seed: 42
  start_index: 500120
  count: 120
  strategy: lhs
  queue_root: configs/train
  preset_hash: sha256:8cf0a7ddc1b7907e2b2cc20e0fe73a2e484d86d476ca12decc3fbf780eeac6d8
  git_sha: dirty:17a95f75c95fc9ccf18ac2d0b593397ceec9c913
  created_at: '2026-05-06T19:45:19Z'
  trial_id: trial_2
  fixed_target:
    rail: 1
    port: sfp_port_0
